version: '3.1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:4.1.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "ke"
  kafkaeagle:
      build:
        context: .
        args:
          KAFKA_ZOOKEEPER_HOSTS: "zookeeper"
      depends_on:
        - kafka
        - mysql
      volumes:
        - ./kafka-secrets/kafka_client_jaas.conf:/kafka-eagle/conf/kafka_client_jaas.conf
      ports:
        - 8048:8048